build_image:
  stage: build
  tags: [ "docker1" ]
  only:
    refs:
    - tags
    changes:
    - dockerfiles/**/*
    - .gitlab-ci.yml
  before_script:
  - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
  - dockerfiles/build.sh
  - dockerfiles/push.sh
