{{- if .Values.switcher.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "fencing.fullname" . }}-switcher
spec:
  selector:
    matchLabels:
      app: {{ template "fencing.fullname" . }}-switcher
  template:
    metadata:
      labels:
        app: {{ template "fencing.fullname" . }}-switcher
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.fencingLabelName }}
                operator: Exists
{{- with .Values.switcher.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
{{- end }}
      serviceAccountName: {{ template "fencing.fullname" . }}
      hostNetwork: true
      imagePullSecrets:
{{ toYaml .Values.switcher.image.pullSecrets | indent 8 }}
      containers:
      - name: fencing-switcher
        image: {{ .Values.switcher.image.repository }}:{{ .Values.switcher.image.tag }}
        imagePullPolicy: {{ .Values.switcher.image.pullPolicy }}
        env:
        - name: FENCING_LABEL
          value: "{{ .Values.fencingLabelName }}"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: DEBUG
          value: "{{ .Values.switcher.debug }}"
{{- end }}
