---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "fencing.fullname" . }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "watch", "get", "delete", "update", "patch", "create"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "fencing.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "fencing.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "fencing.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fencing.fullname" . }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "fencing.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/exec"]
  verbs: ["get", "watch", "list", "create", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "fencing.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "fencing.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "fencing.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
