{{- if .Values.agents.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fencing.fullname" . }}-scripts
data:
{{ toYaml .Values.scripts.scripts | indent 2 }}
---
apiVersion: v1
data: {{- range $key, $value := .Values.scripts.secretEnv }}
  {{ $key | lower }}: {{ $value | b64enc }}
{{- end }}
kind: Secret
metadata:
  name: {{ template "fencing.fullname" . }}-scripts
type: Opaque
{{- end }}
