{{- if .Values.agents.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fencing.fullname" . }}-agents
spec:
  replicas: {{ .Values.agents.replicas }}
  selector:
    matchLabels:
      app: {{ template "fencing.fullname" . }}-agents
  template:
    metadata:
      labels:
        app: {{ template "fencing.fullname" . }}-agents
    spec:
{{- with .Values.agents.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.agents.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
{{- end }}
      hostNetwork: true
      imagePullSecrets:
{{ toYaml .Values.agents.image.pullSecrets | indent 8 }}
      containers:
      - name: fencing-agents
        image: {{ .Values.agents.image.repository }}:{{ .Values.agents.image.tag }}
        imagePullPolicy: {{ .Values.agents.image.pullPolicy }}
        command: [ "/usr/bin/tail", "-f", "/dev/null" ]
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        env:
{{- range $key, $value := .Values.scripts.env }}
          - name: {{ $key }}
            value: {{ $value }}
{{- end }}{{- range $key, $value := .Values.scripts.secretEnv }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                key: {{ $key | lower }}
                name: {{ template "fencing.fullname" $ }}-scripts
{{- end }}
      volumes:
      - name: scripts
        configMap:
          name: {{ template "fencing.fullname" . }}-scripts
          defaultMode: 0744
{{- end }}
