---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fencing
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "watch", "get", "delete", "update", "patch", "create"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fencing
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fencing
subjects:
- kind: ServiceAccount
  name: fencing
  namespace: fencing
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fencing
  namespace: fencing
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fencing
  namespace: fencing
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/exec"]
  verbs: ["get", "watch", "list", "create", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fencing
  namespace: fencing
subjects:
- kind: User
  name: "system:serviceaccount:fencing:fencing"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: fencing
  apiGroup: rbac.authorization.k8s.io
