apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fencing-switcher
  namespace: fencing
spec:
  template:
    metadata:
      labels:
        app: fencing-switcher
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: fencing
                operator: Exists
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      serviceAccountName: fencing
      hostNetwork: true
      hostPID: true
      containers:
      - name: fencing-switcher
        image: kvaps/kube-fencing-switcher
        env:
        - name: FENCING_LABEL
          value: "fencing"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
