apiVersion: v1
kind: ConfigMap
metadata:
  name: fencing-scripts
  namespace: fencing
data:
  fence.sh: |
    #!/bin/bash
    NODE="$1"
    ILO="${NODE}-ilo"
    fence_ilo -a "$ILO" -l user -p password
